# Generated by Django 5.2.7 on 2025-10-21 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [

          ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="member",
            name="joined_date",

           ),
        migrations.RemoveField(
            model_name="member",
            name="lastname",
        ),
        migrations.AddField(
            model_name="member",
            name="user",
            field=models.ForeignKey(

           default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="phone",

     field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
