# Generated by Django 5.2.7 on 2025-10-21 15:57

import django.db.models.deletion
from django.db import migrations, models


class
 Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataFile",
            fields=[
                (
                    "id",

                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,

                 verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (

      "file",
                    models.FileField(blank=True, null=True, upload_to="member_files/"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",

                     models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="members.member",

             ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(

                  fields=["member", "-uploaded_at"],
                        name="datafiles_d_member__2633d2_idx",
                    ),
                    models.Index(fields=["title"], name="datafiles_d_title_64dc26_idx"),
                ],

      },
        ),
    ]
