# Generated by Django 5.2.7 on 2025-10-21 16:26

import datafiles.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datafiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="datafile",
            name="datafiles_d_member__2633d2_idx",

             ),
        migrations.RemoveIndex(
            model_name="datafile",
            name="datafiles_d_title_64dc26_idx",
        ),
        migrations.RemoveField(
            model_name="datafile",
            name="member",
        ),
        migrations.AddField(

             model_name="datafile",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datafiles",
                to=settings.AUTH_USER_MODEL,

             ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="datafile",
            name="file",
            field=models.FileField(
                default=1, upload_to=datafiles.models.user_directory_path

  ),
            preserve_default=False,
        ),
    ]
